/// <reference types="expo/types" />

// NOTE: this file is normally auto-generated by `expo start` (see
// https://docs.expo.dev/router/reference/typed-routes/). It's committed here
// by hand since this sandbox can't run the Expo dev server to generate it.
// Regenerate it for real (and it's fine to overwrite this) the first time
// you run `npx expo start` on a machine with full Expo CLI access.
